version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-staging
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staging_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"

  airflow:
    build: ./airflow
    container_name: airflow
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres:5432/staging_db
      AIRFLOW__CORE__FERNET_KEY: 'D5LmG0-rSgJUG6T6KoE2INqgN5gAcz5dvU2NlZVeDJY='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./data:/opt/airflow/data
    command: standalone

volumes:
  pgdata:
